### ISSUE TITLE
Push docker image to DockerHub and Azure Container Registry

### ISSUE THREAD

**Issue by arschles** [gomods/windows-testing-docker#3]
In https://github.com/gomods/athens/pull/1126, we decided to pre-build an image and then `docker pull` it inside the Athens tests. This repository has that image 🎉 

To make the Athens tests in Azure Pipelines as fast as possible, we need to definitely push this image to Azure Container Registry (ACR) so that the pull from the Athens pipeline tests is fast. We also should push to DockerHub so that this image is public just as the athens image itself is public

**Comment by arschles** [comment]
I am going to take this now

**Comment by arschles** [comment]
@marpio TL;DR the code for this in `azure-pipelines.yml` is 3/4 done. 

https://github.com/gomods/windows-testing-docker/commit/720c1e98c9c51605ab857d2cc3f85681b32a3b92 adds the `docker login` and `docker push` steps. 

It looks like I don't have admin access to the Azure pipeline for this project, so I wasn't able to add the credentials for dockerhub or ACR.

I also am not sure if the `az` CLI is pre-installed on the `win1803` VM. If it's not, I'll need to [do that](https://github.com/gomods/windows-testing-docker/issues/3#issuecomment-479651130) so that `az acr login --name $(acrName)` works.

Let me know what you think!

**Comment by marpio** [comment]
@arschles
You should have the permissions now.
As for the `az` cli - I don't think it's installed but it should be as easy as `choco install azure-cli`
